configurations:
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkButtonTesting/
        - Sources/SparkButtonSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoMockable.stencil
    output: Sources/SparkButtonTesting/Generated/AutoMockable.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkButton]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkButtonTesting/
        - Sources/SparkButtonSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoMockTest.stencil
    output: Sources/SparkButtonTesting/Generated/AutoMockTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkButton]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkButtonTesting/
        - Sources/SparkButtonSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoPublisherTest.stencil
    output: Sources/SparkButtonTesting/Generated/AutoPublisherTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkButton]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkButtonTesting/
        - Sources/SparkButtonSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoViewModelStub.stencil
    output: Sources/SparkButtonTesting/Generated/AutoViewModelStub.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkButton]
